ADMIN ; /web/admin/invites — Gestion de invitaciones pendientes
 ; Subconjunto StackVM: sin dot-blocks; cuerpos de FOR en la misma linea.
 ; Los tokens son [A-Za-z0-9_.-] (saneados en invite_tool) — sin XSS.
 W "<!DOCTYPE html><html><head>"
 W "<meta charset='utf-8'>"
 W "<meta name='viewport' content='width=device-width,initial-scale=1'>"
 W "<style>"
 W "*{margin:0;padding:0;box-sizing:border-box}"
 W "body{font-family:system-ui,sans-serif;padding:16px;max-width:800px;margin:0 auto;background:#0a0a0f;color:#ddd}"
 W "h1{font-size:1.25rem;margin-bottom:.5rem}"
 W ".sub{color:#888;font-size:.75rem;margin-bottom:1rem}"
 W "table{width:100%;border-collapse:collapse;margin-bottom:1rem}"
 W "th,td{padding:.5rem .75rem;text-align:left;border-bottom:1px solid #222;font-size:.875rem}"
 W "th{color:#888;font-weight:500}"
 W "tr:hover{background:#ffffff04}"
 W ".btn{display:inline-block;padding:.25rem .75rem;border-radius:4px;font-size:.75rem;cursor:pointer;border:none;margin-right:.25rem}"
 W ".btn-ok{background:#51cf6622;color:#51cf66;border:1px solid #51cf6644}"
 W ".btn-no{background:#ff6b6b22;color:#ff6b6b;border:1px solid #ff6b6b44}"
 W "</style></head><body>"
 W "<h1>🎫 Invitaciones Pendientes</h1>"
 W "<p class='sub'>Tokens que requieren aprobacion</p>"
 S count=0 S token="" F  S token=$O(^INVITACION("pending",token)) Q:token=""  S count=count+1
 I count=0 W "<p style='color:#888'>No hay invitaciones pendientes ✅</p>"
 I count>0 W "<table><thead><tr><th>Nodo</th><th>Hora</th><th>Token</th><th></th></tr></thead><tbody>"
 S token="" F  S token=$O(^INVITACION("pending",token)) Q:token=""  S data=$G(^INVITACION("pending",token)) S node=$P(data,"|",1) S ts=$E($P(data,"|",2),12,19) W "<tr><td>",node,"</td><td>",ts,"</td><td style='font-family:monospace;font-size:.7rem'>",$E(token,1,16),"...</td><td>","<button class='btn btn-ok' onclick=""fetch('/web/admin/invites/approve?token="_token_"',{method:'POST'}).then(()=>location.reload())"">✓</button>","<button class='btn btn-no' onclick=""fetch('/web/admin/invites/reject?token="_token_"',{method:'POST'}).then(()=>location.reload())"">✕</button>","</td></tr>"
 I count>0 W "</tbody></table>"
 W "<p class='sub'>Limite diario: ",$G(^CONFIG("invite_daily_limit"),5)," | Pendientes: ",count,"</p>"
 W "<p style='margin-top:2rem;font-size:.75rem;color:#555'><a href='/' style='color:#888'>← Home</a></p>"
 W "</body></html>"
 Q
